import type {
  CountryRecord,
  ExpenseCategoryRecord,
  IncomeCategoryRecord,
  IntegrityRuleRecord,
  JurisdictionRecord,
  MileageMethodRecord,
  OccupationRecord,
  ReportSectionRecord,
  TaxYearRecord,
  AssistantCheckRecord,
} from './types';

const L = (fr: string, en: string) => ({ fr, en });

export const fallbackCountries: CountryRecord[] = [
  { code: 'CA', name_i18n: L('Canada', 'Canada'), default_currency: 'CAD', default_distance_unit: 'km' },
  { code: 'US', name_i18n: L('États-Unis', 'United States'), default_currency: 'USD', default_distance_unit: 'mi' },
];

const caProvinces: [string, string, string, string][] = [
  ['AB', 'province', 'Alberta', 'Alberta'],
  ['BC', 'province', 'Colombie-Britannique', 'British Columbia'],
  ['MB', 'province', 'Manitoba', 'Manitoba'],
  ['NB', 'province', 'Nouveau-Brunswick', 'New Brunswick'],
  ['NL', 'province', 'Terre-Neuve-et-Labrador', 'Newfoundland and Labrador'],
  ['NS', 'province', 'Nouvelle-Écosse', 'Nova Scotia'],
  ['NT', 'territory', 'Territoires du Nord-Ouest', 'Northwest Territories'],
  ['NU', 'territory', 'Nunavut', 'Nunavut'],
  ['ON', 'province', 'Ontario', 'Ontario'],
  ['PE', 'province', 'Île-du-Prince-Édouard', 'Prince Edward Island'],
  ['QC', 'province', 'Québec', 'Quebec'],
  ['SK', 'province', 'Saskatchewan', 'Saskatchewan'],
  ['YT', 'territory', 'Yukon', 'Yukon'],
];

const usStates: [string, string, string, string][] = [
  ['AL', 'state', 'Alabama', 'Alabama'],
  ['AK', 'state', 'Alaska', 'Alaska'],
  ['AZ', 'state', 'Arizona', 'Arizona'],
  ['AR', 'state', 'Arkansas', 'Arkansas'],
  ['CA', 'state', 'Californie', 'California'],
  ['CO', 'state', 'Colorado', 'Colorado'],
  ['CT', 'state', 'Connecticut', 'Connecticut'],
  ['DE', 'state', 'Delaware', 'Delaware'],
  ['DC', 'district', 'District de Columbia', 'District of Columbia'],
  ['FL', 'state', 'Floride', 'Florida'],
  ['GA', 'state', 'Géorgie', 'Georgia'],
  ['HI', 'state', 'Hawaï', 'Hawaii'],
  ['ID', 'state', 'Idaho', 'Idaho'],
  ['IL', 'state', 'Illinois', 'Illinois'],
  ['IN', 'state', 'Indiana', 'Indiana'],
  ['IA', 'state', 'Iowa', 'Iowa'],
  ['KS', 'state', 'Kansas', 'Kansas'],
  ['KY', 'state', 'Kentucky', 'Kentucky'],
  ['LA', 'state', 'Louisiane', 'Louisiana'],
  ['ME', 'state', 'Maine', 'Maine'],
  ['MD', 'state', 'Maryland', 'Maryland'],
  ['MA', 'state', 'Massachusetts', 'Massachusetts'],
  ['MI', 'state', 'Michigan', 'Michigan'],
  ['MN', 'state', 'Minnesota', 'Minnesota'],
  ['MS', 'state', 'Mississippi', 'Mississippi'],
  ['MO', 'state', 'Missouri', 'Missouri'],
  ['MT', 'state', 'Montana', 'Montana'],
  ['NE', 'state', 'Nebraska', 'Nebraska'],
  ['NV', 'state', 'Nevada', 'Nevada'],
  ['NH', 'state', 'New Hampshire', 'New Hampshire'],
  ['NJ', 'state', 'New Jersey', 'New Jersey'],
  ['NM', 'state', 'Nouveau-Mexique', 'New Mexico'],
  ['NY', 'state', 'New York', 'New York'],
  ['NC', 'state', 'Caroline du Nord', 'North Carolina'],
  ['ND', 'state', 'Dakota du Nord', 'North Dakota'],
  ['OH', 'state', 'Ohio', 'Ohio'],
  ['OK', 'state', 'Oklahoma', 'Oklahoma'],
  ['OR', 'state', 'Oregon', 'Oregon'],
  ['PA', 'state', 'Pennsylvanie', 'Pennsylvania'],
  ['RI', 'state', 'Rhode Island', 'Rhode Island'],
  ['SC', 'state', 'Caroline du Sud', 'South Carolina'],
  ['SD', 'state', 'Dakota du Sud', 'South Dakota'],
  ['TN', 'state', 'Tennessee', 'Tennessee'],
  ['TX', 'state', 'Texas', 'Texas'],
  ['UT', 'state', 'Utah', 'Utah'],
  ['VT', 'state', 'Vermont', 'Vermont'],
  ['VA', 'state', 'Virginie', 'Virginia'],
  ['WA', 'state', 'Washington', 'Washington'],
  ['WV', 'state', 'Virginie-Occidentale', 'West Virginia'],
  ['WI', 'state', 'Wisconsin', 'Wisconsin'],
  ['WY', 'state', 'Wyoming', 'Wyoming'],
];

export const fallbackJurisdictions: JurisdictionRecord[] = [
  ...caProvinces.map(([code, kind, fr, en]) => ({
    id: `ca-${code.toLowerCase()}`,
    country_code: 'CA',
    code,
    kind,
    name_i18n: L(fr, en),
  })),
  ...usStates.map(([code, kind, fr, en]) => ({
    id: `us-${code.toLowerCase()}`,
    country_code: 'US',
    code,
    kind,
    name_i18n: L(fr, en),
  })),
];

export const fallbackTaxYears: TaxYearRecord[] = [
  { id: 'ca-2025', country_code: 'CA', year: 2025, starts_on: '2025-01-01', ends_on: '2025-12-31', is_current: false },
  { id: 'ca-2026', country_code: 'CA', year: 2026, starts_on: '2026-01-01', ends_on: '2026-12-31', is_current: true },
  { id: 'us-2025', country_code: 'US', year: 2025, starts_on: '2025-01-01', ends_on: '2025-12-31', is_current: false },
  { id: 'us-2026', country_code: 'US', year: 2026, starts_on: '2026-01-01', ends_on: '2026-12-31', is_current: true },
];

export const fallbackOccupations: OccupationRecord[] = [
  { id: 'occ-rideshare', country_code: null, code: 'rideshare', name_i18n: L('Chauffeur covoiturage (Uber, Lyft…)', 'Rideshare driver (Uber, Lyft…)'), sort_order: 10 },
  { id: 'occ-delivery', country_code: null, code: 'delivery', name_i18n: L('Livreur', 'Delivery worker'), sort_order: 20 },
  { id: 'occ-taxi', country_code: null, code: 'taxi', name_i18n: L('Taxi', 'Taxi driver'), sort_order: 30 },
  { id: 'occ-driver', country_code: null, code: 'driver', name_i18n: L('Chauffeur', 'Driver'), sort_order: 40 },
  { id: 'occ-contractor', country_code: null, code: 'contractor', name_i18n: L('Travailleur autonome / contractuel', 'Contractor'), sort_order: 50 },
  { id: 'occ-freelancer', country_code: null, code: 'freelancer', name_i18n: L('Pigiste', 'Freelancer'), sort_order: 60 },
  { id: 'occ-other', country_code: null, code: 'other', name_i18n: L('Autre', 'Other'), sort_order: 90 },
];

function expense(
  country: string,
  code: string,
  fr: string,
  en: string,
  order: number,
  requiresVehicle: boolean,
): ExpenseCategoryRecord {
  return {
    id: `${country.toLowerCase()}-${code}`,
    country_code: country,
    code,
    name_i18n: L(fr, en),
    accountant_label_i18n: L(fr, en),
    sort_order: order,
    requires_receipt: true,
    requires_vehicle: requiresVehicle,
  };
}

export const fallbackExpenseCategories: ExpenseCategoryRecord[] = [
  expense('CA', 'fuel', 'Carburant', 'Fuel', 10, true),
  expense('CA', 'maintenance', 'Entretien', 'Maintenance', 20, true),
  expense('CA', 'repairs', 'Réparations', 'Repairs', 30, true),
  expense('CA', 'parking', 'Stationnement', 'Parking', 40, true),
  expense('CA', 'tolls', 'Péages', 'Tolls', 50, true),
  expense('CA', 'insurance', 'Assurance', 'Insurance', 60, false),
  expense('CA', 'vehicle', 'Frais de véhicule', 'Vehicle expenses', 70, true),
  expense('CA', 'office', 'Frais de bureau', 'Office expenses', 80, false),
  expense('CA', 'phone', 'Téléphone', 'Phone', 90, false),
  expense('CA', 'other', 'Autre', 'Other', 100, false),
  expense('CA', 'car_wash', 'Lavage', 'Car wash', 110, true),
  expense('CA', 'supplies', 'Fournitures', 'Supplies', 120, false),
  expense('CA', 'professional_fees', 'Honoraires professionnels', 'Professional fees', 130, false),
  expense('US', 'fuel', 'Carburant', 'Fuel', 10, true),
  expense('US', 'maintenance', 'Entretien', 'Maintenance', 20, true),
  expense('US', 'repairs', 'Réparations', 'Repairs', 30, true),
  expense('US', 'parking', 'Stationnement', 'Parking', 40, true),
  expense('US', 'tolls', 'Péages', 'Tolls', 50, true),
  expense('US', 'insurance', 'Assurance', 'Insurance', 60, false),
  expense('US', 'vehicle', 'Frais de véhicule', 'Vehicle expenses', 70, true),
  expense('US', 'office', 'Frais de bureau', 'Office expenses', 80, false),
  expense('US', 'phone', 'Téléphone', 'Phone', 90, false),
  expense('US', 'other', 'Autre', 'Other', 100, false),
  expense('US', 'car_wash', 'Lavage', 'Car wash', 110, true),
  expense('US', 'supplies', 'Fournitures', 'Supplies', 120, false),
  expense('US', 'professional_fees', 'Honoraires professionnels', 'Professional fees', 130, false),
];

export const fallbackIncomeCategories: IncomeCategoryRecord[] = [
  { id: 'ca-rideshare', country_code: 'CA', code: 'rideshare', name_i18n: L('Covoiturage / transport de personnes', 'Rideshare'), sort_order: 10 },
  { id: 'ca-delivery', country_code: 'CA', code: 'delivery', name_i18n: L('Livraison', 'Delivery'), sort_order: 20 },
  { id: 'ca-invoiced', country_code: 'CA', code: 'invoiced', name_i18n: L('Facturation client', 'Client invoices'), sort_order: 30 },
  { id: 'ca-tips', country_code: 'CA', code: 'tips', name_i18n: L('Pourboires', 'Tips'), sort_order: 40 },
  { id: 'ca-other', country_code: 'CA', code: 'other', name_i18n: L('Autre revenu', 'Other income'), sort_order: 90 },
  { id: 'us-rideshare', country_code: 'US', code: 'rideshare', name_i18n: L('Rideshare', 'Rideshare'), sort_order: 10 },
  { id: 'us-delivery', country_code: 'US', code: 'delivery', name_i18n: L('Delivery', 'Delivery'), sort_order: 20 },
  { id: 'us-invoiced', country_code: 'US', code: 'invoiced', name_i18n: L('Client invoices', 'Client invoices'), sort_order: 30 },
  { id: 'us-tips', country_code: 'US', code: 'tips', name_i18n: L('Tips', 'Tips'), sort_order: 40 },
  { id: 'us-other', country_code: 'US', code: 'other', name_i18n: L('Other income', 'Other income'), sort_order: 90 },
];

export const fallbackMileageMethods: MileageMethodRecord[] = [
  {
    id: 'ca-cra',
    country_code: 'CA',
    tax_year_id: 'ca-2026',
    method_code: 'cra_per_km',
    title_i18n: L("Taux de l'ARC au kilomètre (référence)", 'CRA per-kilometre rate (reference)'),
    description_i18n: L(
      "Méthode publiée par l'ARC. À valider avec votre comptable. MileTax n'applique pas ce taux.",
      'Method published by the CRA. Confirm with your accountant. MileTax does not apply this rate.',
    ),
    source_name: 'Agence du revenu du Canada',
    source_url: 'https://www.canada.ca/fr/agence-revenu.html',
  },
  {
    id: 'us-irs',
    country_code: 'US',
    tax_year_id: 'us-2026',
    method_code: 'irs_standard_mileage',
    title_i18n: L('Taux standard IRS (référence)', 'IRS standard mileage rate (reference)'),
    description_i18n: L(
      "Taux publié par l'IRS. À valider avec votre comptable. MileTax n'applique pas ce taux.",
      'Rate published by the IRS. Confirm with your accountant. MileTax does not apply this rate.',
    ),
    source_name: 'Internal Revenue Service',
    source_url: 'https://www.irs.gov',
  },
];

export const fallbackReportSections: ReportSectionRecord[] = [
  { id: 'ca-identity', country_code: 'CA', code: 'identity', title_i18n: L('Profil et territoire', 'Profile and jurisdiction'), sort_order: 10, include_entities: ['profile'], notes_i18n: null },
  { id: 'ca-vehicles', country_code: 'CA', code: 'vehicles', title_i18n: L('Véhicules', 'Vehicles'), sort_order: 20, include_entities: ['vehicles'], notes_i18n: null },
  { id: 'ca-mileage', country_code: 'CA', code: 'mileage', title_i18n: L('Kilométrage', 'Mileage'), sort_order: 30, include_entities: ['odometer', 'distance_segments'], notes_i18n: L("Distances calculées entre relevés. Aucun taux n'est appliqué.", 'Distances calculated between readings. No rate is applied.') },
  { id: 'ca-expenses', country_code: 'CA', code: 'expenses', title_i18n: L('Dépenses et reçus', 'Expenses and receipts'), sort_order: 40, include_entities: ['expenses', 'receipts'], notes_i18n: null },
  { id: 'ca-income', country_code: 'CA', code: 'income', title_i18n: L("Revenus d'entreprise", 'Business income'), sort_order: 50, include_entities: ['income'], notes_i18n: null },
  { id: 'ca-completeness', country_code: 'CA', code: 'completeness', title_i18n: L('Points à vérifier', 'Items to review'), sort_order: 60, include_entities: ['integrity'], notes_i18n: null },
  { id: 'us-identity', country_code: 'US', code: 'identity', title_i18n: L('Profil et territoire', 'Profile and jurisdiction'), sort_order: 10, include_entities: ['profile'], notes_i18n: null },
  { id: 'us-vehicles', country_code: 'US', code: 'vehicles', title_i18n: L('Véhicules', 'Vehicles'), sort_order: 20, include_entities: ['vehicles'], notes_i18n: null },
  { id: 'us-mileage', country_code: 'US', code: 'mileage', title_i18n: L('Mileage', 'Mileage'), sort_order: 30, include_entities: ['odometer', 'distance_segments'], notes_i18n: L('Distances calculated between readings. No rate is applied.', 'Distances calculated between readings. No rate is applied.') },
  { id: 'us-expenses', country_code: 'US', code: 'expenses', title_i18n: L('Expenses and receipts', 'Expenses and receipts'), sort_order: 40, include_entities: ['expenses', 'receipts'], notes_i18n: null },
  { id: 'us-income', country_code: 'US', code: 'income', title_i18n: L('Business income', 'Business income'), sort_order: 50, include_entities: ['income'], notes_i18n: null },
  { id: 'us-completeness', country_code: 'US', code: 'completeness', title_i18n: L('Items to review', 'Items to review'), sort_order: 60, include_entities: ['integrity'], notes_i18n: null },
];

export const fallbackIntegrityRules: IntegrityRuleRecord[] = [
  { id: 'r1', code: 'missing_vehicle', entity_type: 'vehicle', severity: 'blocking', title_i18n: L('Aucun véhicule', 'No vehicle'), description_i18n: L('Ajoutez au moins un véhicule pour enregistrer le kilométrage.', 'Add at least one vehicle to record mileage.'), config: {} },
  { id: 'r2', code: 'missing_opening_odometer', entity_type: 'odometer', severity: 'warning', title_i18n: L('Relevé de début manquant', 'Missing opening reading'), description_i18n: L('Aucun relevé de début de période pour ce véhicule cette année.', 'No period-start reading for this vehicle this year.'), config: { kind: 'opening' } },
  { id: 'r3', code: 'odometer_not_monotonic', entity_type: 'odometer', severity: 'blocking', title_i18n: L('Odomètre en baisse', 'Odometer went down'), description_i18n: L('Un relevé est inférieur au précédent. Vérifiez les chiffres.', 'A reading is lower than the previous one.'), config: {} },
  { id: 'r4', code: 'expense_missing_receipt', entity_type: 'expense', severity: 'warning', title_i18n: L('Dépense sans reçu', 'Expense without a receipt'), description_i18n: L('Dépense potentiellement liée à l’activité, sans reçu conservé. À revoir avec votre comptable.', 'Potentially business-related expense, with no receipt on file. Review with your accountant.'), config: {} },
  { id: 'r5', code: 'expense_missing_category', entity_type: 'expense', severity: 'warning', title_i18n: L('Catégorie manquante', 'Missing category'), description_i18n: L('Classez la dépense pour que votre comptable s’y retrouve.', 'Categorize the expense so your accountant can follow it.'), config: {} },
  { id: 'r6', code: 'expense_needs_review', entity_type: 'expense', severity: 'info', title_i18n: L('Dépense à vérifier', 'Expense needs review'), description_i18n: L('Des champs du reçu restent à confirmer. Rien n’est déductible tant que votre comptable n’a pas tranché.', 'Receipt fields still need confirmation. Nothing is a deduction until your accountant reviews it.'), config: {} },
  { id: 'r7', code: 'income_missing_source', entity_type: 'income', severity: 'warning', title_i18n: L('Source de revenu manquante', 'Missing income source'), description_i18n: L('Indiquez la plateforme ou le client.', 'Enter the platform or client.'), config: {} },
  { id: 'r8', code: 'invalid_odometer_reading', entity_type: 'odometer', severity: 'blocking', title_i18n: L('Relevé incohérent', 'Inconsistent reading'), description_i18n: L('Un relevé d’odomètre est inférieur au précédent et n’entre pas dans le kilométrage calculé.', 'An odometer reading is lower than the previous one and is excluded from calculated mileage.'), config: {} },
  { id: 'r9', code: 'missing_end_of_day', entity_type: 'odometer', severity: 'info', title_i18n: L('Odomètre de fin manquant', 'Missing ending odometer'), description_i18n: L('Un début de journée n’a pas encore de relevé de fin.', 'A start-of-day reading does not yet have an end-of-day reading.'), config: {} },
  { id: 'r10', code: 'missing_start_of_day', entity_type: 'odometer', severity: 'warning', title_i18n: L('Odomètre de début manquant', 'Missing beginning odometer'), description_i18n: L('Aucun relevé de début de journée n’est enregistré pour ce véhicule.', 'No start-of-day odometer reading is recorded for this vehicle.'), config: {} },
  { id: 'r11', code: 'expense_incomplete', entity_type: 'expense', severity: 'warning', title_i18n: L('Reçu incomplet', 'Incomplete receipt information'), description_i18n: L('Il manque des informations sur cette dépense potentiellement liée à l’activité. À revoir avec votre comptable.', 'This potentially business-related expense is missing details. Review with your accountant.'), config: {} },
  { id: 'r12', code: 'receipt_pending_review', entity_type: 'expense', severity: 'info', title_i18n: L('Reçu à confirmer', 'Receipt to confirm'), description_i18n: L('Un reçu a été numérisé mais n’a pas encore été relu. Les valeurs extraites restent des suggestions.', 'A receipt was scanned but has not been reviewed yet. Extracted values are still suggestions.'), config: {} },
  { id: 'r13', code: 'missing_activity', entity_type: 'record', severity: 'info', title_i18n: L('Activité manquante', 'Missing activity records'), description_i18n: L('Aucun relevé, reçu ou revenu n’a été ajouté récemment. Compléter le dossier aide votre comptable.', 'No mileage, receipt or income was added recently. Completing the record helps your accountant.'), config: { lookback_days: 7 } },
];

export const fallbackAssistantChecks: AssistantCheckRecord[] = [
  {
    id: 'a1',
    code: 'missing_odometer_reading',
    entity_type: 'odometer',
    default_confidence: 'high',
    title_i18n: L('Relevé d’odomètre manquant', 'Missing odometer reading'),
    description_i18n: L('Un relevé de début, de fin ou d’ouverture semble absent.', 'A start, end or opening odometer reading appears to be missing.'),
    config: { lookback_days: 7 },
  },
  {
    id: 'a2',
    code: 'inconsistent_odometer',
    entity_type: 'odometer',
    default_confidence: 'high',
    title_i18n: L('Relevé d’odomètre incohérent', 'Inconsistent odometer reading'),
    description_i18n: L('Un chiffre enregistré est inférieur au précédent.', 'A recorded reading is lower than the previous one.'),
    config: {},
  },
  {
    id: 'a3',
    code: 'duplicate_receipt',
    entity_type: 'expense',
    default_confidence: 'high',
    title_i18n: L('Reçus possiblement en double', 'Possible duplicate receipts'),
    description_i18n: L('Deux reçus se ressemblent (marchand, date et montant).', 'Two receipts look similar (merchant, date and amount).'),
    config: {},
  },
  {
    id: 'a4',
    code: 'missing_receipt_total',
    entity_type: 'expense',
    default_confidence: 'high',
    title_i18n: L('Total manquant sur un reçu', 'Receipt with a missing total'),
    description_i18n: L('Le montant total n’est pas renseigné, ou n’a pas été lu sur le document.', 'The total amount is missing, or was not read from the document.'),
    config: {},
  },
  {
    id: 'a5',
    code: 'expense_without_document',
    entity_type: 'expense',
    default_confidence: 'high',
    title_i18n: L('Dépense sans pièce justificative', 'Expense without supporting documents'),
    description_i18n: L(
      'Cette dépense potentiellement liée à l’activité n’a pas de reçu conservé. À revoir avec votre comptable.',
      'This potentially business-related expense has no receipt on file. Review with your accountant.',
    ),
    config: {},
  },
  {
    id: 'a6',
    code: 'unusual_expense_amount',
    entity_type: 'expense',
    default_confidence: 'medium',
    title_i18n: L('Montant inhabituel', 'Unusually large expense amount'),
    description_i18n: L(
      'Ce montant sort de vos autres écritures dans la même catégorie. Ce n’est pas un jugement fiscal.',
      'This amount stands out from your other entries in the same category. This is not a tax judgement.',
    ),
    config: { medium_multiplier: 3, high_multiplier: 5, min_sample: 3 },
  },
  {
    id: 'a7',
    code: 'missing_date',
    entity_type: 'record',
    default_confidence: 'high',
    title_i18n: L('Date manquante', 'Missing date'),
    description_i18n: L('Une écriture n’a pas de date utilisable.', 'A record does not have a usable date.'),
    config: {},
  },
  {
    id: 'a8',
    code: 'duplicate_transaction',
    entity_type: 'record',
    default_confidence: 'medium',
    title_i18n: L('Transactions possiblement en double', 'Possible duplicate transactions'),
    description_i18n: L(
      'Deux écritures se ressemblent. Vérifiez qu’il ne s’agit pas du même mouvement.',
      'Two entries look similar. Check that they are not the same movement.',
    ),
    config: {},
  },
  {
    id: 'a9',
    code: 'mileage_gap',
    entity_type: 'odometer',
    default_confidence: 'medium',
    title_i18n: L('Trou dans les relevés de kilométrage', 'Gap in mileage records'),
    description_i18n: L(
      'Plusieurs jours séparent deux relevés valides. Un trou n’est pas forcément une erreur.',
      'Several days separate two valid readings. A gap is not necessarily an error.',
    ),
    config: { gap_days: 31, high_gap_days: 90 },
  },
  {
    id: 'a10',
    code: 'classification_conflict',
    entity_type: 'expense',
    default_confidence: 'needs_review',
    title_i18n: L('Classement personnel / activité à revoir', 'Potential personal/business classification conflict'),
    description_i18n: L(
      'Le classement de cette écriture pourrait mélanger usage personnel et activité. À revoir avec votre comptable. Ce n’est pas une conclusion fiscale.',
      'This entry’s classification might mix personal and business use. Review with your accountant. This is not a tax conclusion.',
    ),
    config: { mixed_use_codes: ['other'] },
  },
];
